export const SHOW_CALENDAR = 'SHOW_CALENDAR'
export const HIDE_CALENDAR = 'HIDE_CALENDAR'

export const SHOW_CLOUD = 'SHOW_CLOUD'
export const HIDE_CLOUD = 'HIDE_CLOUD'

export const SHOW_CREATE_FORM = 'SHOW_CREATE_FORM'
export const SHOW_EDIT_FORM = 'SHOW_EDIT_FORM'
export const HIDE_FORM = 'HIDE_FORM'
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA'

export const SHOW_SEARCH = 'SHOW_SEARCH'
export const HIDE_SEARCH = 'HIDE_SEARCH'
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT'
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING'

export const SHOW_DIALOG = 'SHOW_DIALOG'
export const HIDE_DIALOG = 'HIDE_DIALOG'

export const SET_DATE = 'SET_DATE'
export const UPDATE_TIME = 'UPDATE_TIME'

export const SET_TIME_ELEM_POSITION = 'SET_TIME_ELEM_POSITION'
export const SET_HOURSLINE_ELEM = 'SET_HOURSLINE_ELEM'
export const SET_HOURSLINE_ELEM_POSITION = 'SET_HOURSLINE_ELEM_POSITION'
export const SET_SCROLL = 'SET_SCROLL'
export const SET_PAGE_OVERFLOW = 'SET_PAGE_OVERFLOW'

export const SET_HIGHLIGHTED_ROOM = 'SET_HIGHLIGHTED_ROOM'
export const SET_SELECTED_EVENT = 'SET_SELECTED_EVENT'

export const SET_VALIDATED_DATE = 'SET_VALIDATED_DATE'
export const SET_VALIDATED_TIME_START = 'SET_VALIDATED_TIME_START'
export const SET_VALIDATED_TIME_END = 'SET_VALIDATED_TIME_END'
export const CLEAR_VALIDATED_DATA = 'CLEAR_VALIDATED_DATA'

export const SET_FOCUS = 'SET_FOCUS'

export const FETCH_API = 'FETCH_API'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
